services:
  web:
    build:
      context: ./packages/web
      target: development
    ports:
      - "5173:5173"
    volumes:
      - ./packages/web:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      - NODE_ENV=development
    env_file: .env
    depends_on:
      - db

  scraper:
    build:
      context: ./packages/scraper
    env_file: .env
    depends_on:
      - db

  core:
    build:
      context: ./packages/core
    env_file: .env
    depends_on:
      - db

  db:
    image: postgres:14
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: dbname
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

volumes:
  pgdata:
