services:
  web:
    build:
      context: ./packages/web
      target: production
    ports:
      - "5173:5173"
    environment:
      - NODE_ENV=production
    depends_on:
      - db

  scraper:
    build:
      context: ./packages/scraper
    depends_on:
      - db

  core:
    build:
      context: ./packages/core
    depends_on:
      - db

  db:
    image: postgres:14
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: yourdatabase
      POSTGRES_USER: youruser
      POSTGRES_PASSWORD: yourpassword

volumes:
  pgdata:
